# Generated by Django 5.1.2 on 2025-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_apple_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
