# Generated by Django 5.1.2 on 2025-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0005_food_delete_apple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
