# Generated by Django 5.1.2 on 2025-03-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0008_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(default=200),
        ),
    ]
