# Generated by Django 5.1.2 on 2025-03-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0011_orders_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cost',
            field=models.BigIntegerField(default=200),
        ),
    ]
