# Generated by Django 5.1.2 on 2025-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0012_alter_orders_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.BigIntegerField(default=100),
        ),
    ]
