# Generated by Django 5.1.2 on 2025-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0013_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
